# load_libraries_v003.R
#
# This code segments loads the packages used bt Dr. Craig Slinkman.

# This code segment must be soureced prior to any other code segment that 
# uses any of the libraries.

suppressMessages( library( tidyverse ) )         # I live in the tidyverse ...
suppressMessages( library( lubridate ) )         # For powerful date processing ...
suppressMessages( library( readr ) )             # For raw data input ...
suppressMessages( library( readxl ) )            # To read Excel spreadsheets ...
suppressMessages( library( purrr ) )             # To allow functional prgramming
                                                 # loops ...
suppressMessages( library( Hmisc ))              # To impute missing values ...
suppressMessages( library( stringr ) )           # Consistent string functions ...
suppressMessages( library( modelr ) )            # Regression support packages ...
suppressMessages( library( broom ) )             # Converts regression output to
                                                 # tidy data ...
suppressMessages( library( GGally ) )            # For scatter plot matrix ...
suppressMessages( library( Hmisc ) )             # For data imputation ...
suppressMessages( library( flextable ) )         # For nice table output ...
suppressMessages( library( officer ) )           # For extensions to flextble 
# Microsft Word ...
suppressMessages( library( latex2exp ) )         # Converts laytec notation to
                                                 # R mathemtical exprressions ...
suppressMessages( library( cowplot ) )           # For better looking graphs with
                                                 # ggplot2 ....
#
theme_set( theme_cowplot())                      # Sets cpowplot theme to be the  
                                                 # default theme ...
#




